name: liquid_speech_example
description: Example app for the liquid_speech package.
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.9.0'

dependencies:
  flutter:
    sdk: flutter
  liquid_speech:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
